/// Flutter icons WillBuyItIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WillBuyItIcons
///      fonts:
///       - asset: fonts/WillBuyItIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WillBuyItIcons {
  WillBuyItIcons._();

  static const _kFontFam = 'WillBuyItIcons';
  static const String? _kFontPkg = null;

  static const IconData favourite = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rupee_indian = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
